# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJnDxITKkwIoXlJEuGDMAyAItswGtF_O
"""

import streamlit as st

st.title("Hello, I am T KARTHIKEYA!")
st.header("This is my first streamlit app")
st.subheader("Hospital Appointment Booking and Analysis")

st.write("Welcome to my project! Explore the features and see the predictions.")